<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Configurations>Debug;Release;DebugForceScaffold</Configurations>
    <PackAsTool>true</PackAsTool>
    <Title>Postgresfold.Scaffold.App</Title>
    <Description>Dotnet command line tool for scaffolding c# code from a live PostgreSQL database. Scaffolded code includes: PL/pgSQL functions, c# models, c# domains &amp; c# repositories.</Description>
    <RuntimeIdentifiers>win-x64;osx-x64;osx-arm64;linux-x64;linux-arm64</RuntimeIdentifiers>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.79" />
    <PackageReference Include="Npgsql" Version="9.0.3" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Domain\Postgresfold.Scaffold.Domain\Postgresfold.Scaffold.Domain.csproj" />
    <ProjectReference Include="..\..\Model\Postgresfold.Scaffold.Model\Postgresfold.Scaffold.Model.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="runtimeconfig.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
